[libraries]
annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }
junit-core = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.0" }
fopbot = { module = "org.tudalgo:fopbot", version = "0.6.0" }